# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20160708_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinformation',
            name='country',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinformation',
            name='country',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
