# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20160708_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='duedate',
            field=models.DateField(default='2016-02-05'),
            preserve_default=False,
        ),
    ]
