# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_assignments_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.StudentsInformation')),
            ],
        ),
    ]
