# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20160712_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.StudentsInformation'),
        ),
    ]
